pipeline {
  agent { label 'Jenkins-Agent' }
  tools {
    jdk 'Java17'
    maven 'Maven3'
  }
  stages {
    stage("Cleanup Workspace") {
      steps {
        cleanWs()
      }
    }
    stage("Checkout From SCM") {
      steps {
        git branch: 'main', credentialsId: 'github', url: 'https://github.com/Hatimloha/DevOps_Project.git'
      }
    }
    stage("Build Application") {
      steps {
        sh "mvn clean package"
      }
    }
    stage("Test Application") {
      steps {
        sh "mvn test"
      }
    }
  }
}




Test remain:
  stage("Build Application") {
  steps {
    dir('Deploy_to_Kubernetes_Using') { // Replace 'myapp' with your actual subdirectory name
      sh "mvn clean package"
